# Site settings
title: jedarlington
email: jedarlington@me.com
description: "jedarlington portfolio/blog"
baseurl: ""
url: "http://jedarlington.co.uk"

# Build settings
markdown: kramdown
permalink: pretty
