preferred_syntax = :sass
http_path = '/'
css_dir = '_assets/_stylesheets'
sass_dir = '_assets/_sass'
images_dir = '_assets/_images'
javascripts_dir = '_assets/_js'
relative_assets = true
line_comments = true
# output_style = :compressed